// packages/x6-vue-components/src/split-box/resizer.vue
<template>
  <div
    :style="props.style"
    :className="props.className"
    @mouseDown="onMouseDown"
  />
</template>

<script lang="ts">
import { defineComponent, onBeforeUnmount } from 'vue'
import { MouseMoveTracker } from '../util/dom/MouseMoveTracker'
import { ResizerProps } from './splitbox'

export default defineComponent({
  name: 'Resizer',
  componentName: 'Resizer',
  props: {
    className: {
      type: String,
    },
    style: {
      type: Object,
    },
  },
  emits: ['resizer-mouse-move-end', 'resizer-mouse-move', 'resizer-mouse-down'],
  setup(props: ResizerProps, ctx) {
    // data
    let mouseMoveTracker: MouseMoveTracker
    // methods
    const onMouseMoveEnd = () => {
      mouseMoveTracker.release()
      ctx.emit('resizer-mouse-move-end')
    }

    const onMouseDown = (e: MouseEvent) => {
      mouseMoveTracker.capture(e)
      ctx.emit('resizer-mouse-down', e)
    }

    const onMouseMove = (
      deltaX: number,
      deltaY: number,
      pos?: MouseMoveTracker.ClientPosition,
    ) => {
      ctx.emit('resizer-mouse-move', deltaX, deltaY, pos)
    }
    mouseMoveTracker = new MouseMoveTracker({
      onMouseMove,
      onMouseMoveEnd,
    })

    // lifecycle
    onBeforeUnmount(() => {
      mouseMoveTracker.release()
    })

    return {
      props,
      onMouseDown,
    }
  },
})
</script>

// packages/x6-components/src/split-box/resizer.tsx
import React from 'react'
import { MouseMoveTracker } from '../util/dom/MouseMoveTracker'

export class Resizer extends React.PureComponent<Resizer.Props> {
  private mouseMoveTracker: MouseMoveTracker

  componentWillMount() {
    this.mouseMoveTracker = new MouseMoveTracker({
      onMouseMove: this.onMouseMove,
      onMouseMoveEnd: this.onMouseMoveEnd,
    })
  }

  componentWillUnmount() {
    this.mouseMoveTracker.release()
    delete this.mouseMoveTracker
  }

  onMouseDown = (e: React.MouseEvent) => {
    this.mouseMoveTracker.capture(e)
    this.props.onMouseDown(e)
  }

  onMouseMove = (
    deltaX: number,
    deltaY: number,
    pos: MouseMoveTracker.ClientPosition
  ) => {
    if (this.props.onMouseMove != null) {
      this.props.onMouseMove(deltaX, deltaY, pos)
    }
  }

  onMouseMoveEnd = () => {
    this.mouseMoveTracker.release()
    if (this.props.onMouseMoveEnd != null) {
      this.props.onMouseMoveEnd()
    }
  }

  onClick = (e: React.MouseEvent) => {
    if (this.props.onClick) {
      this.props.onClick(e)
    }
  }

  onDoubleClick = (e: React.MouseEvent) => {
    if (this.props.onDoubleClick) {
      this.props.onDoubleClick(e)
    }
  }

  render() {
    const { className, style } = this.props

    return (
      <div
        style={style}
        className={className}
        onClick={this.onClick}
        onDoubleClick={this.onDoubleClick}
        onMouseDown={this.onMouseDown}
      />
    )
  }
}

export namespace Resizer {
  export interface Props {
    className?: string
    style?: React.CSSProperties
    onClick?: (e: React.MouseEvent) => void
    onDoubleClick?: (e: React.MouseEvent) => void
    onMouseDown: (e: React.MouseEvent) => void
    onMouseMove?: (
      deltaX: number,
      deltaY: number,
      pos: MouseMoveTracker.ClientPosition
    ) => void
    onMouseMoveEnd?: () => void
  }
}
