// packages/x6-angular-shape/src/hook.ts
import { Graph } from '@antv/x6';
import { Content } from './registry';
import { AngularShape } from './node';
import { Injector } from '@angular/core';

declare module '@antv/x6/lib/graph/hook' {
  namespace Hook {
    interface IHook {
      getAngularContent(this: Graph, node: AngularShape): Content;
      getAngularInjector(this: Graph, node: AngularShape): Injector;
    }
  }

  interface Hook {
    getAngularContent(node: AngularShape): Content;
    getAngularInjector(node: AngularShape): Injector;
  }
}

Graph.Hook.prototype.getAngularContent = function (node: AngularShape) {
  let res = node.getContent();
  if (!res) {
    throw new Error(`x6-angular-shape: You have to pass param 'injector' and it should be the instance of TemplateRef or ComponentType!`);
  }
  return res;
};

Graph.Hook.prototype.getAngularInjector = function (node: AngularShape) {
  const res = node.getInjector();
  if (!res) {
    throw new Error(`x6-angular-shape: You have to pass param 'injector' and it should be the instance of Injector!`);
  }
  return res as Injector;
};

// packages/x6-react-shape/src/hook.ts
import { Graph } from '@antv/x6'
import { registry } from './registry'
import { ReactShape } from './node'

declare module '@antv/x6/lib/graph/hook' {
  namespace Hook {
    interface IHook {
      getReactComponent(
        this: Graph,
        node: ReactShape,
      ): React.Component | null | undefined
    }
  }

  interface Hook {
    getReactComponent(
      this: Hook,
      node: ReactShape,
    ): React.Component | null | undefined
  }
}

Graph.Hook.prototype.getReactComponent = function (node: ReactShape) {
  const getReactComponent = this.options.getReactComponent
  if (typeof getReactComponent === 'function') {
    const ret = getReactComponent.call(this.graph, node)
    if (ret != null) {
      return ret
    }
  }

  let ret = node.getComponent()
  if (typeof ret === 'string') {
    const component = registry.get(ret)
    if (component == null) {
      return registry.onNotFound(ret)
    }
    ret = component
  }

  if (typeof ret === 'function') {
    return ret.call(this.graph, node)
  }

  return ret
}
