// packages/x6-react-shape/src/registry.ts
import { Graph, Node, Registry } from '@antv/x6'

export type Definition =
  | ((this: Graph, node: Node) => React.ReactElement | null | undefined)
  | React.ReactElement

export const registry = Registry.create<Definition>({
  type: 'react componnet',
})

declare module '@antv/x6/lib/graph/graph' {
  // eslint-disable-next-line @typescript-eslint/no-shadow
  namespace Graph {
    let registerReactComponent: typeof registry.register
    let unregisterReactComponent: typeof registry.unregister
  }
}

Graph.registerReactComponent = registry.register
Graph.unregisterReactComponent = registry.unregister

// packages/x6-angular-shape/src/registry.ts
import { Component, TemplateRef } from '@angular/core'
import { Graph, Registry } from '@antv/x6'

export type Content = TemplateRef<{}> | Component;

export const registry = Registry.create<Content>({
  type: 'angular componnet',
})

declare module '@antv/x6/lib/graph/graph' {
  // eslint-disable-next-line @typescript-eslint/no-shadow
  namespace Graph {
    let registerAngularContent: typeof registry.register
    let unregisterAngularContent: typeof registry.unregister
  }
}

Graph.registerAngularContent = registry.register
Graph.unregisterAngularContent = registry.unregister
